#!/bin/bash -l
#SBATCH -p regular
#SBATCH --qos=premium
#SBATCH -N 8
#SBATCH -t 02:00:00
#SBATCH -J 4
#
# sbatch myscript.slurm
#---------------------------------
#
pwrun='/global/homes/n/nbrawand/src/epcdft/espresso-5.1.1/bin/pw.x' 
pprun='/global/homes/n/nbrawand/src/epcdft/espresso-5.1.1/bin/epcdft_coupling.x'

srun -n 192 $pwrun < left.in >& left.out
srun -n 192 $pwrun < right.in >& right.out
sh /global/homes/n/nbrawand/src/epcdft/scripts/setup_coupling_input.sh left.out right.out >& coupling.in
srun -n 24 $pprun < coupling.in >& coupling.out
