#!/bin/bash
#COBALT -n 128
#COBALT -t 01:00:00
#COBALT -A CompSpectro
#COBALT --jobname=big
#
# notes:
# run script must be an exe chmod a+x scrpt.sh
# submit the scrpt with qsub --mode script scrpt.sh
#

pwpream="--block $COBALT_PARTNAME -p 8 --envs OMP_NUM_THREADS=1"
cpream="--block $COBALT_PARTNAME -p 8 --envs OMP_NUM_THREADS=1"

pwrun="/home/nbrawand/src/epcdft/espresso-5.1.1/bin/pw.x"
crun="/home/nbrawand/src/epcdft/espresso-5.1.1/bin/epcdft_coupling.x"

runjob $pwpream : $pwrun  < left.in >& left.out
runjob $pwpream : $pwrun  < right.in >& right.out
sh /home/nbrawand/src/epcdft/scripts/setup_coupling_input.sh left.out right.out > coupling.in
runjob $cpream : $crun  < coupling.in >& coupling.out

